- README.md
It seems this is what is done in your own usages of this library. The current readme examples don't work
But this does!
> README: Use theme.enhanceApp({ app })

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Given the high potential for this project to grow, I think it would be a nice idea to start separating bugs and feature requests as early as possible.
- Documentation improvement
> docs: add GitHub issue and PR templates

- src/components/Schema/OASchemaBody.vue
- src/components/Schema/OASchemaTabs.vue
- src/components/ui/badge/index.ts
- src/json.css
- src/style.css
- tailwind.config.js
Changes shadcn-vue theme to re-use VitePress vars to better match style
- Style
> change(styles)!: use VitePress vars to better match theme

- dev/.vitepress/config.ts
- dev/schemas/index.md
- docs/.vitepress/config.mts
- docs/example/schemas/index.md
- docs/public/openapi-schemas.json
- src/components/Common/OACodeBlock.vue
- src/components/Schema/OASchemaBody.vue
- src/components/Schema/OASchemaProperty.vue
- src/components/Schema/OASchemaTabs.vue
- src/lib/generateSchemaJson.ts
- src/lib/hasExample.ts
- test/lib/generateSchemaJson.test.ts
- test/lib/hasExample.test.ts
- test/testsConstants.ts
Allows to handle schema with circular references.
It handles up to 10 levels, inspired by Scalar (https://sandbox.scalar.com/e/o6jBR). It could be configured via `useTheme` composable in the future if needed.
Scalar:
VitePress Theme OpenAPI:
Fixes #57 
- Bug fix
> fix(Schema): handle circular reference and primitive values

- src/components/Path/OAPath.vue
- src/lib/OpenApi.ts
- test/composables/openapi.test.ts
Allows to specify custom Servers for specific Paths.
- https://spec.openapis.org/oas/latest.html#paths-object
- New feature
> feat(operations): allows to specify Path's Servers

- docs/.vitepress/config.mts
- docs/composables/usePlayground.md
- src/components/Try/OARequestParameters.vue
- src/components/Try/OARequestSecurityInput.vue
- src/composables/usePlayground.ts
- src/index.ts
- test/composables/usePlayground.test.ts
- Allows to save Auth Tokens via LocalStorage and share across operations.
- Adds a `usePlayground` composable, to allows to customize Security Scheme default values (and other things in the future).
Closes #59 
- New feature
> feat(playground): allows to save tokens via localStorage

- .github/ISSUE_TEMPLATE/1-bug-report.yml
Change `reproduction` to `reproduction-steps` field. And adds `reproduction` field for URLs to repository/link reproduction.
- CI/CD
> chore(bug issues template): reproduction

- src/composables/useSidebar.ts
- src/style.css
- test/composables/useSidebar.test.ts
Changes de style of SidebarItems to match the default VitePress style. If anyone prefers the previous style, can create a `style.css` file and import it after `import 'vitepress-openapi/dist/style.css'`, with the following styles:
```
.VPSidebarItem:has(.OASidebarItem) .is-link:hover, .VPSidebarItem:has(.OASidebarItem) .is-active {
@apply bg-gray-200 text-gray-900 dark:bg-gray-800 dark:text-gray-100 rounded;
}
.VPSidebarItem:has(.OASidebarItem) .is-link {
@apply text-gray-500 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-800 rounded;
}
.VPSidebarItem:has(.OASidebarItem) .is-active .OASidebarItem-text {
@apply font-semibold;
}
.OASidebarItem-text {
@apply truncate max-w-[170px] text-gray-800 dark:text-gray-100;
}
```
- Breaking change
- Style
> change(sidebar style)!: match VitePress default style

- src/components/Schema/OASchemaPropertyAttributes.vue
Wraps the text inside `code`, to avoid overflow.
Before:
After:
- Style
> fix(schema property value): wrap text

- src/components/Schema/OASchemaTabs.vue
- src/lib/OpenApi.ts
- src/lib/generateSchemaJson.ts
- test/lib/generateSchemaJson.test.ts
Gracefully handles OpenAPI parser exceptions.
Currently, it doesn't handle `anyOf` properly and fails to partialy parse the specification. If any part of the spec causes an error during parsing, the entire spec remains unparsed. However, it now handles exception gracefully and falls back to displaying the original unparsed schema.
- [VitePress OpenAPI](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-qc6frc?file=public%2Fopenapi.json)
- [Sandbox Scalar](https://sandbox.scalar.com/e/3NDUS)
Partially fixes #78 
- Bug fix
> fix(openapi parser): handle exceptions gracefully

- package.json
- src/components/Common/OASpec.vue
- src/components/Path/OAPath.vue
- src/components/Path/OAPaths.vue
- src/components/Path/OAPathsByTags.vue
- src/components/Try/OATryItButton.vue
- src/lib/OpenApi.ts
- src/lib/hasExample.ts
- fix(openapi): avoid parsing spec on every Operation, for better performance when using `OASpec`. May fix #65 
- fix(hasExample): consider `examples`
- chore(try): default Content-Type header when not present
#65 
- Bug fix
> examples && re-use parsedSpec

- docs/composables/useTheme.md
- src/components/Common/Lazy/OALazy.vue
- src/components/Common/Lazy/lazyBus.ts
- src/components/Path/OAPaths.vue
- src/components/Path/OAPathsByTags.vue
- src/components/Try/OATryWithVariables.vue
- src/composables/useTheme.ts
- src/lib/OpenApi.ts
- src/lib/formatJson.ts
- src/lib/formatJsonWithCircularRef.ts
- src/lib/generateSchemaJson.ts
- src/lib/hasExample.ts
- test/composables/useTheme.test.ts
- test/lib/formatJsonWithCircularRef.test.ts
- Adds an option to avoid circular references when parsing schemas
- Adds an option to lazy render Tags and Operations (for larger schemas)
#65 
- New feature
> feat: avoidCirculars && lazyRendering

- docs/composables/useTheme.md
- package.json
- src/components/Path/OAPathsByTags.vue
- src/composables/useOpenapi.ts
- src/composables/usePaths.ts
- src/composables/useSidebar.ts
- src/composables/useTheme.ts
- src/lib/OpenApi.ts
- src/lib/generateMissingTags.ts
- src/lib/transformSpec.ts
- test/composables/openapi.test.ts
- test/composables/useSidebar.test.ts
- test/composables/useTheme.test.ts
Adds a `generateMissingTags` function to set a `defaultTag` for operations that has no tags, as a Tag is needed for sidebar/routing to group operations without tags.
#105 (Just saw this issue when testing the reproduction)
- Bug fix
> fix(spec): generate defaultTag for operations that has no tags

- src/components/Path/OAPathsByTags.vue
Escapes to `{` and `}` characters to allows to navigate via hash.
Fixes #108 
- Bug fix
> fix(PathsSummary): allows to navigate to Operations with {} chars

- docs/layouts/sidebar.md
- src/composables/useSidebar.ts
Allows to customize Method Bag via `methodAliases` option in `useSidebar` composable.
Closes #118 
- New feature
> feat(useSidebar): methodAliases option to customize method bag

- dev/.vitepress/theme/components/ThemeConfiguration.vue
- docs/.vitepress/config.mts
- docs/customizations/operation-tags-slot.md
- docs/customizations/parts/operation-tags-slot-example.md
- package.json
- src/components/Operation/OAOperation.vue
- src/components/Operation/OAOperationTags.vue
- src/components/Path/OAPath.vue
- src/components/Playground/OAPlaygroundParameters.vue
- src/composables/useTheme.ts
- src/index.ts
- src/locales/en.json
- src/locales/es.json
- src/types.ts
- test/composables/useTheme.test.ts
- Adds an optional `tags` slot that shows every Operation Tag as a Badge
- Change vertical spacing between Operations Slots to make it more compact
- Fix default authorization selected scheme in Playground
Closes #120 
- Bug fix 
- New feature
> feat(Operation): tags slot

- src/lib/getSchemaUi.ts
- test/lib/getSchemaUi.test.ts
Handle array of items without type, by determining the type from the value.
Closes #131
- New feature
> feat(schema): handle array of items without type

- docs/sidebar/sidebar-items.md
- src/composables/useSidebar.ts
- src/lib/sidebar/generateSidebarItemsByPaths.ts
- test/composables/useSidebar.itemsByPaths.test.ts
Allows to specify a custom `sidebarGroupTemplate` when using `itemsByPaths` from `useSidebar` composable.
Closes #163 
- New feature
> feat(useSidebar): allows to specify sidebarGroupTemplate in itemsByPaths

- src/components/Playground/OAPlaygroundParameters.vue
- src/types.ts
- test/lib/getSecurityUi.test.ts
For ApiKey Authorizations, use HeaderName as Header, instead of SchemeName
Closes #168 
- Bug fix
> fix(codeSamples): header name for ApiKey auth

- src/components/Playground/OAPlaygroundResponse.vue
Before it was disabling html transform when body has > 1000 rows. Now it's > 1000 chars.
- New feature
> change(CodeBlocks): disable html transform when body has > 1000 chars

- package.json
- pnpm-lock.yaml
Currently installing package within non-tailwindcss project
with `pnpm` and `strict-peer-dependencies=true` is failing with:
```
(project package)
└─┬ vitepress-openapi 0.0.3-alpha.65
└─┬ tailwindcss-animate 1.0.7
└── ✕ missing peer tailwindcss@">=3.0.0 || insiders"
Peer dependencies that should be installed:
tailwindcss@">=3.0.0 || insiders"
```
> chore(package): move tailwind packages to `devDependencies`

- package.json
- src/components/Playground/OAPlayground.vue
- src/composables/usePlayground.ts
- src/lib/codeSamples/buildHarRequest.ts
- test/composables/usePlayground.submitRequest.test.ts
The playground was adding the `Content-Type` header twice. Once as `content-type` and once as `Content-Type`. This resulted in incorrect headers being sent with the request, causing the requests to fail.
Fixes #192 
- Bug fix
> fix(Playground): remove duplicated Content-Type header

- docs/sidebar/sidebar-items.md
- docs/sidebars.ts
- src/composables/useTheme.ts
This PR replaces the current defaultHeaders by an empty object.
The current defaultHeaders add `--header 'Content-Type: application/json'` to curl code examples. While some default headers might be useful for certain APIs, having `'Content-Type: application/json'` for all requests (including GET) does not make much sense as a default.
- Breaking change _(fix or feature that would cause existing functionality to change)_: Users who rely on the current Content-Type would need to add it explicitly.
> fix(codeSamples)!: empty defaultHeaders

- docs/.vitepress/theme/components/BrowserWindow.vue
- docs/.vitepress/theme/components/ExampleBlock.vue
- docs/.vitepress/theme/components/sandbox/SandboxIframe.vue
- docs/customizations/code-samples.md
- docs/customizations/custom-server.md
- docs/customizations/custom-slots.md
- docs/customizations/operation-badges.md
- docs/customizations/operation-tags-slot.md
- docs/public/openapi-parameters.json
- docs/sidebar/sidebar-items.md
- src/components/Feature/OAOperationContent.vue
- src/components/Feature/OASpecContent.vue
- src/components/Sample/OACodeSamples.vue
- src/composables/useTheme.ts
- test/composables/useTheme.test.ts
- test/lib/processOpenAPI/__snapshots__/processOpenAPI.test.ts.snap
Add support for `vitepress-plugin-group-icons` to show icons in Code Samples.
Closes #198 
- Style
> feat(CodeSamples): add support for `vitepress-plugin-group-icons` to show icons in Code Samples

- docs/guide/getting-started.md
- docs/public/openapi-schemas.json
- src/lib/examples/getSchemaUiJson.ts
- src/lib/parser/getSchemaUi.ts
- test/lib/processOpenAPI/getSchemaUi.test.ts
Adds support for schemas with `type: ["object", "null"]`
Closes #206 
- New feature
> feat(Schemas): support nullable object types

- docs/composables/useTheme.md
- src/components/Common/OAJSONEditor.vue
- src/components/Playground/OAPlaygroundResponseContent.vue
- src/composables/useTheme.ts
The JSON editor was emitting the JSON as String, which flipped the input type from structured JSON (objects) to plain text (strings).
- Bug fix
> fix(OAJSONEditor): parse JSON value before emitting update

- docs/public/openapi-schemas.json
- src/lib/examples/getSchemaUiJson.ts
- src/lib/parser/getSchemaUi.ts
- test/lib/processOpenAPI/getSchemaUi.test.ts
Adds support for `prefixItems` in Schema UI.
Closes #125, #111
- New feature
> feat(openapi): add support for prefixItems

- docs/public/openapi-schemas.json
- src/components/Schema/OASchemaUI.vue
- src/lib/examples/getSchemaUiJson.ts
- src/lib/parser/getSchemaUi.ts
- test/lib/processOpenAPI/getSchemaUi.test.ts
This PR adds support for `anyOf` schemas and improves support for `oneOf` schemas as well.
Consider an OpenAPI spec that uses a schema object like this one:
```yaml
PetWithTag: 
type: "object"
properties: 
pet: 
description: "Full pet object **or** numeric pet ID"
oneOf: 
- $ref: "#/components/schemas/Cat"
- type: "integer"
description: "Pet ID"
tag: 
description: "Structured tag object **or** plain-text label"
anyOf: 
- $ref: "#/components/schemas/TagInfo"
- type: "string"
description: "Free-text label"
required: 
- "pet"
- "tag"
```
Notice the following issues:
* The `tag` display is incomplete: in the schema it is `anyOf` `TagInfo definition` | `string`, but on the page it appears as just `string`.
* Absence of the `Required` label on the `pet` property.
* The type of the `pet` …
> feat: add support for anyOf schemas and improve handling of anyOf/oneOf

- src/index.ts
- src/lib/parser/generateCodeSamples.ts
- src/lib/parser/generateMissingOperationIds.ts
- src/lib/parser/generateMissingSummary.ts
- src/lib/parser/generateMissingTags.ts
- src/lib/parser/generateRequestBodyUi.ts
- src/lib/parser/generateResponseUi.ts
- src/lib/parser/generateSecurityUi.ts
- test/lib/prepareOpenAPI/generateMissingOperationIds.test.ts
- test/lib/prepareOpenAPI/generateMissingSummary.test.ts
- test/lib/prepareOpenAPI/generateMissingTags.test.ts
- test/lib/processOpenAPI/parseOpenapi.pathMetadata.test.ts
OpenAPI spec allows metadata fields like `summary` or `description` at the Path Item Object level: https://spec.openapis.org/oas/v3.0.4.html#path-item-object.
However, a spec like the one below leads to a crash due to the incorrect assumption that all keys of a Path Item Object are HTTP verbs / objects:
```yaml
openapi: "3.0.0"
info: 
title: "Minimal API"
version: "1.0.0"
paths: 
/example: 
summary: "Example endpoint"
description: "This path supports both GET and POST methods."
get: 
responses: 
200: 
description: "OK"
post: 
responses: 
201: 
description: "Created"
```
This produced the following error:
```
TypeError: Cannot create property 'operationId' on string 'This path supports both GET and POST methods.'
```
* Parser utilities now iterate only over supported HTTP verbs (now …
> fix: Crash when `Path Item Object` has a field other than HTTP verb

- src/components/Feature/OAServersContent.vue
This PR fixes text overflow in the "servers" block when the text contains long, unbreakable words like long URLs or similar content.
Before:
After:
> fix: overflow of long unbreakable text in 'servers' block

- src/lib/OpenApi.ts
- test/composables/openapi.test.ts
According to the OpenAPI specification (3.1, 3.0, and earlier), the ["servers" field in the Path Item Object](https://spec.openapis.org/oas/latest.html#path-item-object), as well as in the [Operation Object](https://spec.openapis.org/oas/latest.html#operation-object), overrides (not merges with) any servers defined at higher levels.
This PR updates the `OpenApi` lib function to respect that specification and ensures that when "servers" are defined at both the OpenAPI Object level and the _Path_ and/or _Operation_ level, the lower-level "servers" take precedence and override the higher-level ones.
> fix: respect OpenAPI servers precedence rules

- src/composables/useSidebar.ts
- test/composables/useSidebar.multipleTags.test.ts
This PR fixes an issue with sidebar rendering when multiple operations have multiple tags, and tags are repeated across operations.
Consider this spec:
```yaml
paths:
/api/cats:
get:
tags:
- 'mammal'
- 'cat'
- 'fluffy'
summary: 'Find a cat'
operationId: 'findCat'
responses:
200:
description: 'OK'
/api/sphynxs:
get:
tags:
- 'mammal'
- 'cat'
- 'bald'
summary: 'Find a sphynx cat'
operationId: 'findSphynx'
responses:
200:
description: 'OK'
/api/fancyrats:
get:
tags:
- 'mammal'
- 'fluffy'
- 'small'
- 'rat'
summary: 'Find a fancy rat'
operationId: 'findFancyRat'
responses:
200:
description: 'OK'
/api/lizards:
get:
tags:
- 'small'
- 'reptile'
- 'lizard'
summary: 'Find a lizard'
operationId: 'findLizard'
responses:
200:
description: 'OK'
/account/stats:
get:
summary: 'Get user stats'
operationId: …
```
> fix: render sidebar items with multiple tags in all groups

- src/components/Common/OACodeValue.vue
- src/components/Schema/OASchemaPropertyAttributes.vue
- src/lib/parser/getSchemaUi.ts
- test/lib/processOpenAPI/getSchemaUi.test.ts
This improves UI display of enums and default values, as well as enums with default values.
```json
"components": {
"schemas": {
"Pet": {
"type": "object",
"properties": {
"petType": {
"type": "string",
"enum": ["cat", "dog", "lizard"],
"default": "cat"
},
"hasFur": {
"type": ["boolean", "null"],
"default": null
},
"paws": {
"type": "number",
"default": 4
},
"classifierCode": {
"type": "string",
"default": "4"
},
"color": {
"enum": ["red", "amber", "green", false, 42, "42", null]
}
}
}
}
}
```
There are a few problems:
* No default value for `petType` (root cause - because it is an **enum**)
* No default value for `hasFur` (root cause - because its `"default"` is `null` — see [here](https://github.com/OAI/OpenAPI-Specification/issues/2057) the discussion about `null` default values in OA …
> feat: improve UI for default values and enums

- src/lib/parser/dereferenceWithAnnotations.ts
- src/lib/parser/resolveCircularRef.ts
- test/lib/processOpenAPI/parseOpenapi.circularRef.test.ts
Well, so after #256 followed by #268, I realized that the initial implementation of a custom dereferencer introduced in #256 was incorrect, as @enzonotario noticed - it broke circular reference handling, leading to the schema type being displayed as `string` in the UI instead of showing the proper object shape with a `Circular Reference` badge where the recursion starts.
In #256, the existing `dereferenceSync` from **@trojs/openapi-dereference** was replaced with a custom dereference implementation (`dereferenceWithAnnotationsSync`), which was based on the @trojs version but enhanced to handle cases where schema annotations ("default", "description", etc.) were present on the same level as `$ref`. To add annotations to the referenced object, we - unlike `dereferenceSync` from @trojs - …
> fix: ensure proper circular references detection

- docs/composables/useTheme.md
- docs/customizations/operation-links.md
- src/composables/useMarkdown.ts
- src/composables/useTheme.ts
- test/composables/useMarkdown.test.ts
- test/composables/useTheme.test.ts
As a follow-up to [this conversation](https://github.com/enzonotario/vitepress-openapi/pull/260#issuecomment-3066121489), this PR adds a new option `markdown.config` to `useTheme()`, which accepts a callback with a `markdown-it` instance as an argument. This allows users to customize Markdown rendering across the specification and its schemas in the UI, by applying their own plugins or replacing the `markdown-it` instance with their own if they prefer.
**Usage example and use-case**
Let's say your spec description fields contain something like JSDoc-style links (a real case if you generate schemas [from TypeScript](https://github.com/vega/ts-json-schema-generator)!). You want to process them as if they were regular Markdown links.
Now you can do, for example:
```ts
useTheme({
markdown: { …
```
> feat: add `markdown.config` option to `useTheme()` to allow `markdown‑it` customization

- docs/public/openapi-schemas.json
- src/components/Schema/OASchemaUI.vue
- src/lib/parser/getSchemaUi.ts
- test/lib/processOpenAPI/getSchemaUi.test.ts
Currently, if the schema type is `"array"` and its `"items"` are of a primitive type like `"string"`, the UI doesn't display annotations for those item schemas.
```json
{
"type": "object",
"properties": {
"foo": {
"type": "string",
"description": "String with a constraint",
"maxLength": 30
},
"bar": {
"type": "array",
"description": "An array where each item is a string with a constraint",
"items": {
"type": "string",
"description": "String with a constraint",
"maxLength": 30
}
},
"baz": {
"type": "string",
"enum": ["red", "green"],
"description": "Enum string"
},
"qux": {
"type": "array",
"items": {
"type": "string",
"enum": ["red", "green"],
"description": "Enum string"
},
"description": "An array where each item is a enum string"
},
"grox": {
"anyOf": [
{
"type": "string", …
```
> fix: display the complete UI for array items of primitive type

- docs/public/openapi.json
- src/components/Response/OAResponse.vue
- test/lib/processOpenAPI/__snapshots__/processOpenAPI.test.ts.snap
According to the OpenAPI spec, Markdown **may** be used in the description field [of the Response Object](https://spec.openapis.org/oas/latest.html#response-object).
But the `OAResponse` component rendered the description as plain text.
Considering that descriptions across the whole UI are rendered with `OAMarkdown`, this is probably just a small oversight. This PR updates the Response descriptions to be rendered by the `OAMarkdown` component as well.
UI Before:
UI After:
> fix: Render "Responses" descriptions with OAMarkdown component

- src/components/Schema/OASchemaUI.vue
Since we always call `t(titleCase(key))` in `OASchemaPropertyAttributes.vue`, wrapping `'Valid values'` in one more `t('Valid values')` call in `OASchemaUI.vue` is unnecessary and leads to console warnings like
```sh
[vue-i18n] Message "Valores válidos" not found  
```
when using a locale other than `en`.
A small oversight introduced by #267.
This PR fixes it by removing redundant call in `OASchemaUI.vue`.
> fix: remove redundant `t()` call in OASchemaUI.vue

- src/components/Parameter/OAParameter.vue
Currently, there is some level of inconsistency between labels in `OAParameter` and `OASchemaUI`. For example:
When the Parameter Object uses a schema with the `"enum"` field, the Parameter UI shows `Enum` label, while the identical schema in the Request/Response body uses `Valid values` phrase.
Additionally, for property attributes such as `default`, `maxLength`, etc., there was no internationalization. As a result, where the Request/Response body shows "Por defecto" (e.g., in `es` locale), the Parameter UI shows "default" (non-localized), which adds more inconsistency.
This PR fixes this by replacing `t('Enum')` with `t('Valid values')` in `OAParameter.vue` (aligned with `OASchemaUI.vue`) and passing `name` (parameter attribute name) to `t(titleCase(name))`, which is identical to how …
> fix: Make labels used in `OAParameter` align with those in `OASchemaUI`

- docs/composables/useTheme.md
- src/components/Schema/OASchemaUI.vue
- src/composables/useTheme.ts
- test/composables/useTheme.test.ts
Currently, in `OASchemaUI.vue`, the open state for each child component is determined by the `open` prop. This prop is set with the expression:
```vue
<OASchemaUI
...
:open="childrenExpandState !== undefined ? childrenExpandState : isUnion"
...
/>
```
Because this expression always yields a boolean (either `childrenExpandState` when defined or `isUnion` when not), the `open` prop is never `undefined` for nested schemas. Consequently, `isOpen` is always initialized using this provided value instead of using `props.deep` logic:
```ts
const isOpen = ref(props.open !== undefined ? props.open : props.deep > 0 && props.level <= 10)
```
This makes the configuration option `schemaViewer.deep` useless, as it doesn't affect the rendering of OASchemaUI in any way.
This PR:
* Fixes that by passing …
> fix: respect `schemaViewer.deep` option in OASchemaUI
