.github/workflows/publish-commit.yml, README.md, dev/.vitepress/theme/index.ts, package.json, src/composables/useTheme.ts, src/config.ts, src/index.ts
=> feat(composables) useTheme to manage settings

README.md, docs/guide/getting-started.md
After testing briefly with V2, it turns out V3 is needed?
=> README, state OAPI v3 requirement

package.json
Adding this so that I can easily rebuild
this while including it directly into my
development project
(Hopfully I can open some PRs)
=> Add build-watch command

src/composables/useOpenapi.ts
=> Error on non v3 spec being provided

src/components/Try/OARequestParameters.vue
=> fix(OARequestParameters) baseUrl

package.json, src/components/Common/OAOperation.vue, src/components/Path/OAPath.vue, src/components/Path/OAPathEndpoint.vue, src/components/Try/OATryWithVariables.vue, src/composables/useTheme.ts
- change(OAOperation) move to own Slot
- feat(useTheme) `showBaseUrl` setting
=> change(OAOperation) move to own Slot

docs/.vitepress/config.mts, docs/layouts/custom-slots.md, package.json, src/components/Common/OAOperation.vue, src/components/Path/OAPath.vue, src/components/Response/OAResponses.vue
- Change responses tabs design
- Add `path-mobile` slot
=> Responses tab design

tailwind.config.js
Fixes incorrect usage of css var.
- Bug fix
=> fix(tailwind config): background var

.github/workflows/lint.yml, eslint.config.js, package.json, src/components/Common/OAFooter.vue, src/components/Common/OAHeading.vue, src/components/Common/OAOperation.vue, src/components/Playground/OAPlaygroundResponse.vue, src/components/Sample/OACodeSamples.vue, src/components/Schema/OASchemaPropertyAttributes.vue, src/components/Try/OATryItButton.vue, src/env.d.ts, src/json.css, src/lib/OpenApi.ts, src/lib/fetchToCurl.ts
Adds a `lint` action to run on every PR, for standardizing code style.
- CI/CD
=> chore(repo): add lint action

src/components/Common/OAOperation.vue
Wraps Try section in `ClientOnly` to avoid SSR, since it includes client-only code.
#65 
- Bug fix
=> change(Try section): avoid SSR

dev/.vitepress/config.ts, dev/scalar-galaxy/index.md, docs/index.md, docs/public/openapi-scalar-galaxy.json, docs/public/openapi.json, package.json, src/components/Common/OAOperation.vue, src/components/Security/OASecurity.vue, src/components/Security/OASecurityContent.vue, src/components/Try/OARequestParameters.vue, src/components/Try/OARequestSecurityInput.vue, src/composables/useTheme.ts, src/locales/en.json, src/locales/es.json
Adds a Select to select current SecurityScheme to use.
- New feature
=> change(authorizations): allows to switch via Select

docs/.vitepress/config.mts, docs/.vitepress/theme/index.ts, docs/composables/useTheme.md, docs/customizations/operation-badges.md, docs/layouts/multiple-specs.md, src/components/Common/OAHeaderBadges.vue, src/components/Common/OAOperation.vue, src/composables/useTheme.ts, src/index.ts, src/locales/en.json, src/locales/es.json, src/locales/index.ts, test/composables/useTheme.test.ts
Allows to customize Badges to shown above Operations. Also allows to configure i18n and passing custom `messages`.
- New feature
=> Operation Badges && i18n configuration

docs/layouts/custom-slots.md, package.json, src/components/Response/OAResponse.vue, src/components/Schema/OASchemaBody.vue, src/lib/generateSchemaJson.ts, src/locales/en.json, src/locales/es.json, test/lib/generateSchemaJson.test.ts, test/testsConstants.ts
Allows to handle schema with ContentTypes.
- New feature
=> feat(schemas): handle schemas with content types

dev/.vitepress/config.ts, dev/index.md, dev/multiple-specs.md, docs/.vitepress/config.mts, docs/example/introduction.md, docs/layouts/info-servers.md, docs/public/openapi.json, src/components/Common/OAInfo.vue, src/components/Common/OAServers.vue, src/components/Common/OASpec.vue, src/components/index.ts
Exposes `OAInfo` and `OAServers` components.
- New feature
=> feat(components): OAInfo and OAServers

dev/.vitepress/theme/index.ts, src/composables/useSidebar.ts, src/composables/useTheme.ts, src/index.ts, test/composables/useSidebar.test.ts
- Fix SSR Hydration Mismatch error when rendering sidebar items
- Fix i18n setup
Fixes #84 
- Bug fix
=> fix(i18n): locale and fallbackLocale setup

dev/.vitepress/theme/components/ThemeConfiguration.vue, dev/one-page.md, docs/.vitepress/config.mts, docs/composables/useTheme.md, docs/example/one-page.md, docs/tailwind.config.js, src/components/Common/OAMethodBadge.vue, src/components/Common/OASpec.vue, src/components/Path/OAPathEndpoint.vue, src/components/Path/OAPaths.vue, src/components/Path/OAPathsByTags.vue, src/components/Path/OAPathsSummary.vue, src/components/Try/OATryItButton.vue, src/components/index.ts, src/components/ui/button/index.ts, src/composables/useSidebar.ts, src/composables/useTheme.ts, src/index.ts, src/lib/OpenApi.ts, src/locales/en.json, src/locales/es.json, src/style.css, tailwind.config.js, test/composables/openapi.test.ts, test/composables/useOpenapiWithNoSpec.test.ts, test/composables/useSidebar.test.ts, test/composables/useTheme.test.ts, test/testsConstants.ts
Allows to group paths by tags.
Closes #81 
- New feature
=> feat(Spec): group by tags

docs/.vitepress/config.mts, docs/example/parameters/index.md, docs/public/openapi-parameters.json, src/components/Playground/OAPlaygroundParameterInput.vue, src/components/Playground/OAPlaygroundParameters.vue
Allows to handle Boolean Parameters with a Checkbox.
Fixes #83 
- Bug fix
- New feature
=> fix(playground variables): handle Boolean parameters with Checkbox

package.json, src/components/Common/OACodeValue.vue, src/components/Parameter/OAParameter.vue, src/components/Schema/OASchemaPropertyAttributes.vue, src/locales/en.json, src/locales/es.json
Shows example/s value for Parameters
Closes #93 
- New feature
=> feat(OAParameter): show example/s value/s

dev/one-page.md, dev/operations/[operationId].md, src/components/Path/OAPathsByTags.vue
Adds checks for window/element existence before trigger scrollIntoView.
- Bug fix
- New feature
=> chore(OAPathsByTags): window checks for scrollIntoView

dev/one-page.md, src/components/Common/OASpec.vue, src/components/Operation/OAOperation.vue, src/components/Path/OAPath.vue, src/components/Path/OAPaths.vue, src/components/Path/OAPathsByTags.vue, src/components/index.ts, src/types.ts
- Exposes OAOperation slots to be able to extend them in OASpec
- Separated branding/footer slots 
- New feature
=> slots && branding

dev/.vitepress/theme/components/ThemeConfiguration.vue, dev/criptoya-argentina/index.md, dev/one-page.md, docs/composables/useTheme.md, docs/example/one-page.md, package.json, pnpm-lock.yaml, src/components/Operation/OAOperation.vue, src/components/Path/OAPath.vue, src/components/Path/OAPaths.vue, src/components/Path/OAPathsByTags.vue, src/composables/useTheme.ts, src/types.ts, test/composables/useTheme.test.ts
Allows to configure `OAOperation` slots and cols via `useTheme` for better customization.
Closes #91 
- New feature
=> feat(useTheme): allows to configure operation's slots and cols

dev/.vitepress/config.ts, dev/tags/[tag].md, dev/tags/[tag].paths.js, docs/.vitepress/config.mts, docs/example/tags/[tag].md, docs/example/tags/[tag].paths.js, docs/layouts/pages-by-tags.md, docs/layouts/sidebar.md, src/components/Common/OASpec.vue, src/components/Path/OAPathsByTags.vue, src/composables/usePaths.ts, src/composables/useSidebar.ts, src/lib/OpenApi.ts, test/composables/openapi.test.ts, test/composables/usePaths.test.ts, test/composables/useSidebar.test.ts, test/testsConstants.ts
Allows to generate pages by tags
- New feature
=> Pages by tags

docs/layouts/sidebar.md, package.json, src/components/Schema/OASchemaTabs.vue, src/components/ui/tabs/index.ts, src/composables/usePaths.ts, src/composables/useSidebar.ts, src/lib/OpenApi.ts
Removes border of Schema Tabs to have a bit more spacing and better match with theme.
- Style
=> change(theme): Schema Tabs without borders

docs/composables/useTheme.md
Changes wrong config.
Closes #107
- Documentation improvement
=> docs(useTheme): fix `requestBody` config

docs/.vitepress/config.mts, src/composables/useTheme.ts, src/lib/OpenApi.ts, src/lib/generateMissingTags.ts, test/composables/openapi.test.ts, test/composables/useTheme.test.ts
Allows to specify `description` for Default Tag.
#109
- New feature
=> feat(useTheme): add `defaultTagDescription` config

dev/.vitepress/config.ts, docs/.vitepress/config.mts, docs/layouts/sidebar.md, src/composables/useSidebar.ts, src/lib/sidebar/cleanSidebarItems.ts, src/lib/sidebar/ensureGroupTextSlashPrefix.ts, src/lib/sidebar/flatSidebarItems.ts, src/lib/sidebar/generateSidebarItemsByPaths.ts, src/lib/sidebar/mergeAdjacentGroups.ts, src/lib/sidebar/setItemCollapsedState.ts, test/composables/useSidebar.itemsByPaths.test.ts, test/lib/sidebar/ensureGroupTextSlashPrefix.test.ts, test/lib/sidebar/mergeAdjacentGroups.test.ts, test/lib/sidebar/setItemCollapsedState.test.ts
Allows to generate Sidebar Items by Paths.
- Closes #119 
- New feature
=> feat(sidebar): Generate items by Paths

docs/composables/useTheme.md, docs/public/openapi.json, package.json, src/components/Parameter/OAParameter.vue, src/composables/useTheme.ts, src/lib/constraintsParser.ts, src/lib/getExamples.ts, src/locales/en.json, src/locales/es.json, src/locales/pt-BR.json, test/composables/useTheme.test.ts, test/lib/__snapshots__/processOpenAPI.test.ts.snap, test/lib/constraintsParser.test.ts, test/lib/getExamples.test.ts
Shows parameters constraints as key-value.
- Closes #123
- Closes #130 
- New feature
=> feat(parameters): constraints and examples

docs/layouts/sidebar.md, package.json, src/composables/useSidebar.ts, src/lib/sidebar/generateSidebarItemsByPaths.ts, test/composables/useSidebar.itemsByPaths.test.ts
=> fix(sidebar): change collapsable by collapsible option

dev/.vitepress/config.ts, docs/.vitepress/config.mts, docs/composables/useTheme.md, docs/customizations/i18n.md, docs/public/openapi-response-statuses.json, package.json, src/components/Common/OALocaleSelect.vue, src/components/index.ts, src/components/ui/select/SelectContent.vue, src/composables/useSidebar.ts, src/composables/useTheme.ts, src/index.ts, test/composables/useTheme.test.ts
- Allows to change Locale dynamically
- New `OALocaleSelect` component 
- Closes #128 
- New feature
=> feat(i18n): dynamic locale and OALocaleSelect component

dev/.vitepress/theme/components/sandbox/Sandbox.vue, dev/.vitepress/theme/components/sandbox/SandboxPreview.vue, src/components/Path/OAPathsByTags.vue, src/components/Remote/OARemoteOperation.vue, src/components/index.ts, src/lib/utils.ts
- Adds `OARemoteOperation`
- Change z-index for Sandbox Nav
- New feature
=> feat: OARemoteOperation 

tailwind.config.js
Removes container style from Tailwind config.
- Style
=> fix(style): container size

docs/.vitepress/theme/components/sandbox/Sandbox.vue, docs/sandbox/index.md, src/components/Path/OAPath.vue, src/components/Playground/OAPlaygroundParameters.vue, src/lib/utils.ts
Safely access `localStorage` and `window` to avoid errors during build time or SSR.
Closes #154 
- Bug fix
=> fix: safe access to localStorage and window

docs/public/showcases.json
Incorporando la sección de Showcase, La documentación de ejemplo de una API utilizando esta herramienta.
=> docs(showcase): add pyDolarVenezuela API

src/components/Security/OASecurityContent.vue
Uses `details/summary` to show the flows of OAuth Security Scheme.
- Style
=> change(Security): use details/summary for OAuth flows

src/lib/processOpenAPI/getSchemaUi.ts, test/lib/getSchemaUi.test.ts
- Bug fix _(non-breaking change which fixes an issue)_
- New feature _(non-breaking change which adds functionality)_
- Breaking change _(fix or feature that would cause existing functionality to change)_
- Documentation improvement
- Style _(Change that do not affect the functionality of the code)_
- CI/CD _(Changes to the CI/CD configuration)_
=> fix(schema): add enum descriptions

.github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/run-test.yml, src/components/Sample/OACodeSamples.vue
Reapply `immediate` flag to `watch` in `OACodeSamples`.
- Refactor
=> fix(OACodeSamples): reapply immediate flag to watcher

test/composables/openapi.test.ts
=> test(OpenApi): add tests for setSpec, getSpec, and getFilteredTags methods

src/lib/codeSamples/buildHarRequest.ts, src/lib/codeSamples/buildRequest.ts, test/lib/buildRequest.test.ts, test/lib/codeSamples/buildHarRequest.test.ts, test/lib/codeSamples/generateCodeSamples.test.ts
Decodes previously encoded URLs for better displaying.
Closes #223 
- New feature
=> feat(request): decode URL strings for better Code Samples

docs/.vitepress/theme/components/ExampleBlock.vue, docs/.vitepress/theme/components/SlotDebugger.vue, docs/.vitepress/theme/index.ts, docs/customizations/custom-slots.md, docs/customizations/parts/custom-slots-example.md, src/components/Common/Highlight/OAVueJsonPretty.vue, src/components/index.ts
Closes #229 
- Documentation improvement
=> chore(docs): update custom slots documentation and examples with SlotDebugger

src/components/index.ts
=> feat(exports): export components: parameter, path, request, response, and playground

docs/public/showcases.json
Added AeroDB APi documentation to showcases.json
New entry in showcases list
=> Added AeroDB to showcases.json
